sudo: required

services:
  - docker

before_install:
  - docker-compose up -d

install:
  - docker exec -it phpeventstoreclient_php_1 bash -c "cd /var/www && composer install --prefer-dist --no-interaction"

script:
  - docker exec -it phpeventstoreclient_php_1 bash -c "cd /var/www && bin/phpunit --coverage-clover=coverage.clover --coverage-text --testdox"

after_success:
  - docker exec -it phpeventstoreclient_php_1 bash -c "cd /var/www && wget https://scrutinizer-ci.com/ocular.phar"
  - docker exec -it phpeventstoreclient_php_1 bash -c "cd /var/www && php ocular.phar code-coverage:upload --format=php-clover coverage.clover"

after_scripts:
  - killall -SIGINT clusternode
